# Generated by Django 4.1.7 on 2023-03-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Zaposlenici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime", models.CharField(max_length=100)),
                ("prezime", models.CharField(max_length=100)),
                (
                    "slika",
                    models.ImageField(default="avatar.svg", null=True, upload_to=""),
                ),
                (
                    "spol",
                    models.CharField(
                        choices=[("M", "Muško"), ("Z", "Žensko")], max_length=1
                    ),
                ),
                ("god_rod", models.PositiveIntegerField()),
                ("pocetak_rada", models.DateField(auto_now_add=True)),
                ("vrsta_ugovora", models.BooleanField()),
                ("trajanje", models.DateField(blank=True, null=True)),
                ("odjel", models.CharField(max_length=100)),
                ("br_godisnji", models.PositiveIntegerField(blank=True, null=True)),
                ("br_slob", models.PositiveIntegerField(blank=True, null=True)),
                ("br_dopust", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
