# Generated by Django 4.1.7 on 2023-03-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_odjeli_alter_zaposlenici_odjel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zaposlenici",
            name="spol",
            field=models.CharField(
                choices=[
                    ("M", "Muško"),
                    ("Z", "Žensko"),
                    ("O", "Ostalo"),
                    ("NE", "Ne želim reći"),
                ],
                max_length=2,
            ),
        ),
    ]
